// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgUg7ptt0s0rP9lD9gmzuxF8SqGVa7cRQ',
    appId: '1:573150666152:web:b654689b407c37c64a119d',
    messagingSenderId: '573150666152',
    projectId: 'camwonders',
    authDomain: 'camwonders.firebaseapp.com',
    storageBucket: 'camwonders.appspot.com',
    measurementId: 'G-B6S1KNBHYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSwQLDNJaotIxiZWaMpaw5ai60gnS6lus',
    appId: '1:573150666152:android:38099d05e96f3f394a119d',
    messagingSenderId: '573150666152',
    projectId: 'camwonders',
    storageBucket: 'camwonders.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzWrFFfA1q45Bxpkq2fmqGd4lU6HjLqrU',
    appId: '1:573150666152:ios:264585ba7da9ac164a119d',
    messagingSenderId: '573150666152',
    projectId: 'camwonders',
    storageBucket: 'camwonders.appspot.com',
    iosClientId: '573150666152-cod0vnbem2ihbngdhi67r8m3vllas5iu.apps.googleusercontent.com',
    iosBundleId: 'com.example.camwonders',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzWrFFfA1q45Bxpkq2fmqGd4lU6HjLqrU',
    appId: '1:573150666152:ios:264585ba7da9ac164a119d',
    messagingSenderId: '573150666152',
    projectId: 'camwonders',
    storageBucket: 'camwonders.appspot.com',
    iosClientId: '573150666152-cod0vnbem2ihbngdhi67r8m3vllas5iu.apps.googleusercontent.com',
    iosBundleId: 'com.example.camwonders',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgUg7ptt0s0rP9lD9gmzuxF8SqGVa7cRQ',
    appId: '1:573150666152:web:f49049bcada648e44a119d',
    messagingSenderId: '573150666152',
    projectId: 'camwonders',
    authDomain: 'camwonders.firebaseapp.com',
    storageBucket: 'camwonders.appspot.com',
    measurementId: 'G-L4JKLVQE1J',
  );
}
