workflows:
  ios:
    name: Build iOS
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      flutter: stable
    scripts:
      - cd ios
      - pod init
      - cd ..
      - flutter clean
      - flutter pub get
      - flutter build ios --release
